# Generated by Django 2.2.5 on 2019-09-26 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название филиала')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название провайдера')),
                ('contract', models.CharField(max_length=20, verbose_name='Договор')),
                ('entity', models.CharField(max_length=40, verbose_name='Юр. лицо')),
                ('tel_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер магазина')),
                ('address', models.CharField(max_length=80, verbose_name='Адрес магазина')),
                ('tel_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Filial')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.Provider')),
            ],
        ),
    ]
