# Generated by Django 2.2.5 on 2019-09-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='speed',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='Скорость'),
        ),
    ]
