# Generated by Django 2.2.5 on 2019-09-27 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_shop_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='License_Astor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TS', models.CharField(max_length=20, verbose_name='Лицензия ТС7')),
                ('SIS', models.CharField(max_length=20, verbose_name='Лицензия SIS')),
                ('MDT', models.CharField(max_length=20, verbose_name='Лицензия MDT')),
                ('LP', models.CharField(max_length=20, verbose_name='Лицензия LabelPrint')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.Shop')),
            ],
        ),
    ]
