# Generated by Django 2.2.5 on 2019-09-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20190927_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='kass_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество касс'),
        ),
    ]
