# Generated by Django 2.2.5 on 2019-09-27 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_shop_kass_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='license_astor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='hello.License_Astor'),
        ),
    ]
