# Generated by Django 2.2.5 on 2019-10-01 08:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20190927_0354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Провайдер', 'verbose_name_plural': 'Провайдеры'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AddField(
            model_name='shop',
            name='time_closet',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Закрытие'),
        ),
        migrations.AddField(
            model_name='shop',
            name='time_open',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Открытие'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='filial',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hello.Filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='license_astor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hello.License_Astor', verbose_name='Лицензии Астор'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Номер магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='provider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='hello.Provider', verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Скорость'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
    ]
