# Generated by Django 2.2.5 on 2019-10-01 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20191001_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='time_closet',
        ),
        migrations.AddField(
            model_name='shop',
            name='time_close',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Закрытие'),
        ),
    ]
