# Generated by Django 2.2.5 on 2019-12-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20191001_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Картридж')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Cartridge_journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время выдачи')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Cartridge', verbose_name='Картридж')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Картриджи',
            },
        ),
    ]
