# Generated by Django 2.2.5 on 2019-12-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_cartridge_cartridge_journal_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge_journal',
            options={'verbose_name': 'Журнал', 'verbose_name_plural': 'Журнал'},
        ),
        migrations.AlterField(
            model_name='cartridge_journal',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время выдачи'),
        ),
    ]
