# Generated by Django 2.2.5 on 2019-12-30 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20191226_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge_journal',
            name='time',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата выдачи'),
        ),
    ]
